version: "3.2"
services:
  database:
    container_name: database
    image: oscarfonts/h2
    environment:
      - H2_OPTIONS=-ifNotExists
    ports:
      - 1521:1521
      - 81:81

  application:
    container_name: chebit-app
    build: .
    ports:
      - 8282:8282
    depends_on:
      - database
