server:
  port: 8282
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chebit?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: nesty
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:h2:tcp://localhost/~/chebit
    #url: jdbc:h2:tcp://localhost:1521/demo
#    username: sa
 #   password:
  #  driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true 로그로 찍는것
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace